#!/bin/sh
set -ex

cleanup() {
    echo "Exiting with $?"
}
trap cleanup EXIT

# cargo fmt --check
# cargo check
# cargo audit -D unmaintained -D yanked
# cargo clippy
cargo build
# cargo nextest run

idxr() { 
    ./target/debug/mina-indexer "$@" 
}

blocks() {
    ./target/debug/mina-blocks "$@"
}

# Block Downloader binary exists
mkdir $TMP/blocks
blocks 2>&1 |
    grep -iq "Usage:"
rm -rf $TMP/blocks

# Indexer reports usage with no arguments
idxr 2>&1 | 
    grep -iq "Usage:"

# Indexer reports usage for server subcommand
idxr server 2>&1 |
    grep -iq "Usage: mina-indexer server"

# Indexer reports usage for client subcommand
idxr client 2>&1 | 
    grep -iq "Usage: mina-indexer client"

# Indexer server config subcommand exists
idxr server config 2>&1 | 
    grep -iq "Usage: mina-indexer server config"

# Indexer server cli subcommand works
idxr server cli --help > /dev/null

# Indexer server config parses empty yaml config file
idxr server config --path ./tests/empty.config.yaml 2>&1 |
    grep -iq "Error:"

# Indexer server config parses minimal yaml config file
rm -rf ${TMP}/{startup,watch,rocksdb,logs}
mkdir -p ${TMP}/{startup,watch,rocksdb,logs}
idxr server config --path ./tests/minimal.config.yaml &
export IDXR_PID=$(pgrep "mina-indexer" | head)
idxr client summary > $TMP/summary | echo
cat $TMP/summary |
    grep "Error: Connection refused (os error 111)"
kill $IDXR_PID
rm -rf ${TMP}/{startup,watch,rocksdb,logs,summary}
wait

echo  "All Tests Passed! :)"