#!/bin/sh
set -ex

cleanup() {
    echo "Exiting with $?"
    IDXR_PID=$(pgrep mina-indexer)
    kill $IDXR_PID
    wait
}
trap cleanup EXIT

# cargo fmt --check
# cargo check
# cargo audit -D unmaintained -D yanked
# cargo clippy
cargo build
# cargo nextest run

idxr() { 
    ./target/debug/mina-indexer "$@" 
}

# Indexer reports usage with no arguments
idxr 2>&1 | 
    grep -iq "Usage:"

# Indexer reports usage for server subcommand
idxr server 2>&1 |
    grep -iq "Usage: mina-indexer server"

# Indexer reports usage for client subcommand
idxr client 2>&1 | 
    grep -iq "Usage: mina-indexer client"

# Indexer server config subcommand exists
idxr server config 2>&1 | 
    grep -iq "Usage: mina-indexer server config"

# Indexer server cli subcommand works
idxr server cli --help > /dev/null

# Indexer server cli starts with minimum required args
idxr server cli \
    --initial-ledger tests/ledgers/mainnet-genesis.json \
    --is-genesis-ledger \
    --root-hash 3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ &
IDXR_PID=$(pgrep mina-indexer)
kill $IDXR_PID
wait

# Indexer server cli can be queried immediately
idxr server cli \
    --initial-ledger tests/ledgers/mainnet-genesis.json \
    --is-genesis-ledger \
    --root-hash 3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ &
sleep 5
idxr client best-chain -n 100
IDXR_PID=$(pgrep mina-indexer)
kill $IDXR_PID
wait

echo "Done"