#!/bin/sh
set -ex

setup() {
    mkdir $TMP/mina-blocks
    mkdir -p ${TMP}/{startup,watch,rocksdb,logs}
}

cleanup() {
    echo "Exiting with $?"
    rm -rf $TMP/mina-blocks
    rm -rf ${TMP}/{startup,watch,rocksdb,logs}
}
count_files() {
    find $1 ! -wholename $1 -prune -print | grep -c /
}
trap cleanup EXIT
setup()

# cargo fmt --check
# cargo check
# cargo audit -D unmaintained -D yanked
# cargo clippy
cargo build
# cargo nextest run

idxr() { 
    ./target/debug/mina-indexer "$@" 
}

blocks() {
    ./target/debug/mina-blocks "$@"
}

# Block Downloader binary exists
blocks 2>&1 |
    grep "Usage: mina-blocks"

# Block Downloader binary downloads blocks from heights 0-5
blocks -n 5 -s 0 -o $TMP/mina-blocks -m mainnet -b mina_network_blocks
if [ $(count_files $TMP/mina-blocks) != 5 ]; then
    ls $TMP/mina-blocks
    exit 1
fi

# Indexer reports usage with no arguments
idxr 2>&1 | 
    grep -iq "Usage:"

# Indexer reports usage for server subcommand
idxr server 2>&1 |
    grep -iq "Usage: mina-indexer server"

# Indexer reports usage for client subcommand
idxr client 2>&1 | 
    grep -iq "Usage: mina-indexer client"

# Indexer server config subcommand exists
idxr server config 2>&1 | 
    grep -iq "Usage: mina-indexer server config"

# Indexer server cli subcommand works
idxr server cli --help > /dev/null

# Indexer server config parses empty yaml config file
idxr server config --path ./tests/empty.config.yaml 2>&1 |
    grep -iq "Error:"

# Indexer server config parses minimal yaml config file
idxr server config --path ./tests/minimal.config.yaml &
export IDXR_PID=$(pgrep "mina-indexer" | head)
idxr client summary > $TMP/summary | echo
cat $TMP/summary |
    grep "Error: Connection refused (os error 111)"
kill $IDXR_PID
wait

echo  "All Tests Passed! :)"